services:
  postgresql:
    image: postgres:latest
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testpassword
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: {}
